### ISSUE TITLE
User registration

### ISSUE THREAD

**Issue by hunghuytran** [Arcada-Devops-2017/frontend#1]
Användargränssnitt:
- Email
- Namn
- Lösenord
- Registeringsknapp

Funktioner:
Skicka information till Auth.
Registering.
Email verifiering?/skip

**Comment by Tebro** [comment]
Email verifiering anser jag att vi inte behöver ta med i projektets scope, eftersom det har en del externa dependencies.

**Comment by hunghuytran** [comment]
Sign up är lyckad.
