### ISSUE TITLE
User login

### ISSUE THREAD

**Issue by hunghuytran** [Arcada-Devops-2017/frontend#2]
Användargränssnitt:
- Användarnamn fält
- Lösenord fält
- Log in knapp
- Glömt lösenord

Användaren ska kunna logga in (Auth)
Updatering av användare?/skip

Username = email
glömt lösenord = tar dej till en sida var vi har vår contact support email

**Comment by MishClaw** [comment]
Hung succesfully tested the login today with auth api.
