### ISSUE TITLE
Draft layout

### ISSUE THREAD

**Issue by hunghuytran** [Arcada-Devops-2017/frontend#8]
Exempel på layout.

**Comment by Emsamm** [comment]
https://cdn.discordapp.com/attachments/353530794255319040/355347224827527168/Arcada_devops_desktopHP.png

**Comment by Emsamm** [comment]
https://cdn.discordapp.com/attachments/353530794255319040/355347343920463872/Arcada_devops_mobileHP.png

**Comment by MishClaw** [comment]
layout done and already quite ahead
